### ISSUE TITLE
fire CI only on final PRs and not draft PRs

### ISSUE THREAD

**Issue by brent-greenwood** [elastic/dbt#25]
**Is your feature request related to a problem? Please describe.**
was just drafting the PR to get eyeballs on all of the changes, but not yet ready for final PR review.  

**Describe the solution you'd like**
don't run CI or post msg to Slack for draft PRs

**Describe alternatives you've considered**
if necessary, I can just not create draft PRs

**Additional context**
def not major issue, but would be nice to be able to use draft status while finishing up dev pre-CI

**Comment by lord-skinner** [comment]
Integration testing will now only run on pull requests against main that are marked `ready_for_review`.  

Commit is [here](https://github.com/elastic/dbt/commit/e597497bc39dfee1e462cbb5e4aada59a0f885a5).
